-- Deprecated: do not execute this historical cleanup script.
--
-- Service-order permission changes are released through:
--   deploy/migrations/0001_service_order_permissions.sql
--
-- Legacy physical-order rows are intentionally retained for one-release code
-- rollback compatibility. Current application code filters them from role
-- menus and backend access sets. Physical deletion belongs in a later migration
-- after the previous release is no longer a supported rollback target.
